# Generated by Django 6.0.1 on 2026-01-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="加密后的病患姓名", max_length=255),
                ),
                ("age", models.IntegerField(help_text="年龄")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        help_text="性别",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpectrumRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(help_text="原始光谱文件路径", max_length=500),
                ),
                (
                    "processed_path",
                    models.CharField(
                        blank=True,
                        help_text="预处理后数据路径",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "diagnosis_result",
                    models.CharField(
                        blank=True,
                        help_text="诊断结果 (Benign/Malignant)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, help_text="置信度 (0.0 - 1.0)", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="上传时间"),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(default=False, help_text="是否经医生复核"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="关联病患",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="raman_api.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="上传医生",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Administrator"), ("doctor", "Doctor")],
                        default="doctor",
                        help_text="用户角色",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
