# Generated by Django 5.2.9 on 2026-01-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raman_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectrumrecord",
            name="is_training_data",
            field=models.BooleanField(default=False, help_text="是否作为训练集"),
        ),
        migrations.AddField(
            model_name="spectrumrecord",
            name="metadata",
            field=models.JSONField(
                blank=True, help_text="元数据 (ER, HER2, etc)", null=True
            ),
        ),
        migrations.AddField(
            model_name="spectrumrecord",
            name="spectral_data",
            field=models.JSONField(
                blank=True, help_text="光谱数据 {'x': [], 'y': []}", null=True
            ),
        ),
    ]
