# Generated by Django 5.2.9 on 2026-01-29 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raman_api", "0002_spectrumrecord_is_training_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="版本号 (e.g. v1.0.0)", max_length=50, unique=True
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="模型文件路径 (.pkl/.pth)", max_length=500
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(blank=True, help_text="验证集准确率", null=True),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, help_text="详细指标 (Precision, Recall)", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="是否为当前生产模型"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosisFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_diagnosis", models.CharField(max_length=50)),
                ("corrected_diagnosis", models.CharField(max_length=50)),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="raman_api.spectrumrecord",
                    ),
                ),
            ],
        ),
    ]
